### ISSUE TITLE
Consider `check_trailing_bits=false` for BASE64_MIME decoder

### ISSUE THREAD

**Issue by wathiede** [ia0/data-encoding#102]
In https://github.com/staktrace/mailparse/issues/96 it was considered to request this package allow trailing bits on the BASE64_MIME codec.  The assumptions behind this reasoning are:
* BASE64_MIME is tailored for email
* in real world emails are sometimes imperfect, and returning something is better than nothing

Would this project be willing to accept a pull request that makes BASE64_MIME more liberal in its handling by setting `check_trailing_bits=false`? If not, that's okay, I can go back to the mailparse project and see if they're willing to handle it.

Note, I'm not associated with the project, I just personally stumbled across this problem recently, so I figured I'd start with their suggestion first.

**Comment by ia0** [comment]
There's at least 3 options:
- The solution in https://github.com/staktrace/mailparse/issues/96 which is to define their own encoding with lazy-static.
- Using data-encoding-macro which doesn't need lazy-initialization because it produces the encoding at compile-time (see below for a snippet).
- Add a `BASE64_MIME_PERMISSIVE` constant in data-encoding. (I'm not willing to change the behavior of `BASE64_MIME` because this would be a breaking change. But adding a new constant for those who need to ignore trailing bits is fine.)

```rust
const BASE64_MIME_PERMISSIVE: data_encoding::Encoding = data_encoding_macro::new_encoding! {
    symbols: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    padding: '=',
    check_trailing_bits: false, // NEW (defaults to true)
    wrap_width: 76,
    wrap_separator: "\r\n",
};
```

What do you think? Happy to add `BASE64_MIME_PERMISSIVE` if that's what you would prefer.
