### ISSUE TITLE
Add `examples/encode/main.rs` to include for use with `cargo install --example`

### ISSUE THREAD

**Issue by Celti** [ia0/data-encoding#2]
`encode` is an incredibly useful utility all in its own right — most Linux/UNIX systems do not come with base32 or hexadecimal decoders/encoders in their repositories, or if they do they are often written in slow interpreted languages.

While it's entirely possible to clone the repository and run `make encode`, it's far easier for many users (especially on, e.g., Windows) to run `cargo install data-encoding --example encode` to have a completely platform-independent method of installing it.

Unfortunately, without adding the file to the include array in Cargo.toml, it won't be included in the crate for installation.

**Comment by ia0** [comment]
Hi @Celti,

Thanks for the feedback! I was not convinced that the `encode` program would be useful enough to release it. In particular, for hexadecimal I know `xxd`, and base32 and base64 are in coreutils. Note that the `base32` program has been added by [89c517d](http://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=commit;h=89c517d9e26ad232d857ba37d897adbef19b30a9) during September 2015, so it's maybe not on all distributions yet.

Another reason was that I was not satisfied enough with the `encode` program to release it (in particular what should the command-line look like). But this is in my todo list to release a generic program dealing with encodings, so it will be done at some point (maybe in one or two months).

In the meantime, would the following command suits you?
```
cargo install --example encode --git https://github.com/ia0/data-encoding.git data-encoding
```
You can use `--tag v1.1.2` to install the current release instead of the master branch.

If using `git` is an issue (I don't know Windows enough), I am fine adding the `encode` program, in its current example state, to the crate in a v1.2.0 version. The reason I did not do so in the first place, was to have a light crate for faster downloads.

Thanks for your interest!
Julien

**Comment by Celti** [comment]
Heh, I already have it installed, in fact, so it's no big deal on my part — I just felt such a useful tool should be easier for people to access.

As for coreutils, I had totally missed base32 now being part of it, which is very good to know — but xxd, at least on Arch, is part of Vim and definitely *not* part of the base system — and according to current coreutils git tree, not part of coreutils either.

Regardless, if you have a generic program for the whole deal on your TODO list, then I will happily wait for that, and keep using the example utility as-is in the meantime.

Thanks for the response — closing.

**Comment by ia0** [comment]
Oh I misunderstood :-) That's great then!

Indeed, `xxd` is part of `vim` and not part of the base system. But I suspect it's quite often installed by default. Anyway I will also take its features into account when rewriting `encode` since `xxd` allows to patch files, which is something base32 and base64 don't do.

Cheers!

**Comment by ia0** [comment]
@Celti By the way, since you were interested in a simple way to install the binary, I now have released the binary as an independent [crate]. It is possible to install it with `cargo install data-encoding-bin` and the binary will be called `data-encoding`. It also provides more options than the previous example binary.

[crate]: https://crates.io/crates/data-encoding-bin

**Comment by Celti** [comment]
Beautiful! Thank you muchly for this one.
