### ISSUE TITLE
check_trailing_bits still errors at certain lengths for base32

### ISSUE THREAD

**Issue by robyoder** [ia0/data-encoding#28]
When using `spec.check_trailing_bits = false;` with the base32 spec, I would expect that any string of base32 characters would be decoded successfully with any extra bits ignored. But this is not the case. For strings with a length congruent to 1, 3, or 6 (mod 8), a `DecodeError` is thrown.

```rust
use data_encoding::{BASE32_NOPAD, DecodeError};

fn main() {
    println!("{:?}", decode(b"77777777"));
    println!("{:?}", decode(b"777777777"));
    println!("{:?}", decode(b"7777777777"));
}

fn decode(bytes: &[u8]) -> Result<Vec<u8>, DecodeError> {
    let mut spec = BASE32_NOPAD.specification();
    spec.check_trailing_bits = false;

    spec.encoding().unwrap().decode(bytes)
}
```

The above code produces the following output:

```
Ok([255, 255, 255, 255, 255])
Err(DecodeError { position: 8, kind: Length })
Ok([255, 255, 255, 255, 255, 255])
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8ad9b0a736dfb48ed469d171f893d929)

I understand that by [the canonical definition in the RFC](https://tools.ietf.org/html/rfc4648#section-3.5), the second input is invalid base32, but so is the third, and I would expect them to be treated the same when it comes to `check_trailing_bits`. So for this example, I would expect the second line in the output to be identical to the first.

Is the current behavior in this circumstance intentional, or is it simply a matter of a length check being done first without concern for `check_trailing_bits`?

For reference, [Google Authenticator for Android follows my expectation](https://github.com/google/google-authenticator-android/blob/efac95c88ef8d9f8be3c887fbcd2c2fdf4f45dbe/java/com/google/android/apps/authenticator/util/Base32String.java#L27-L30) in this regard, as does Authy for iOS (in my own testing). In the comment linked there you can see that a "string of sixteen 7s ("7...7") and seventeen 7s both decode to the same byte array", which is not the case here.

**Comment by ia0** [comment]
Thank you @robyoder for the report.

This is actually expected behavior. The `check_trailing_bits` permits to configure the behavior for the trailing bits of the last byte (for valid length inputs) and not the trailing bytes. There is currently no convenience configuration to accept inputs of invalid length. Maybe it would be useful to add one, please open an issue if you would benefit from such feature.

However there is a way to decode inputs of invalid lengths using the `position` of the `Length` error when calling `decode` (see [documentation](https://docs.rs/data-encoding/2.1.2/data_encoding/struct.Encoding.html#method.decode)). This has very small overhead and can be done with a convenience `truncate_decode` function:

```rust
fn truncate_decode(encoding: &Encoding, input: &[u8]) -> Result<Vec<u8>, DecodeError> {
    match encoding.decode(input) {
        Err(DecodeError {
            position,
            kind: DecodeKind::Length,
        }) => encoding.decode(&input[..position]),
        output => output,
    }
}
```
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0b729b4b174330e8ff0f4791b88628ba)

**Comment by robyoder** [comment]
Sure, we can work around it and we will, but probably without running the decode function twice. 

My question is this: what is the benefit of having `check_trailing_bits` for only the cases it currently covers? If some algorithm is generating base32 (or some other base) with trailing bits that are not zeros, isn't it plausible that it would also be generating base32 with trailing characters?

One such algorithm would be a naive secret generator that selects characters at random from the base32 alphabet. The final character in the string may represent 1-4 trailing bits, or a full 5 extra bits. I'm curious what kinds of algorithms `check_trailing_bits` is designed to accommodate if not one like this.

**Comment by jpgoldberg** [comment]
> Sure, we can work around it and we will, but probably without running the decode function twice.

Note that it only decodes a second time on that error. But I don't care one way or the other when we do the truncation.

> My question is this: what is the benefit of having `check_trailing_bits` for only the cases it currently covers?

I guess that the "length" condition and the "trailing bits" condition are seen as two independent conditions. But that, of course, misses the point of the length condition (as I understand it).

> If some algorithm is generating base32 (or some other base) with trailing bits that are not zeros, isn't it plausible that it would also be generating base32 with trailing characters?

Well-formedness conditions may reasonably be separated from thinking about the kinds of algorithms that might generate funky input. But my real suspicion is that the problem we are seeing doesn't show up in base64 and so hasn't really been thought about.

**Comment by jpgoldberg** [comment]
> But my real suspicion is that the problem we are seeing doesn't show up in base64 and so hasn't really been thought about.

Nope. In B64, the same thing happens in the 1 mod 4 case. So much more that bit of speculation.

**Comment by ia0** [comment]
You're not running the decode function twice, you're just calling it twice on invalid input and one call returns immediately. The `truncate_decode` has very low overhead as I said (a few nanoseconds) because the length check is done before everything else. The content of the input is not read at all. This is actually one of the reasons why checking length is a different check than checking trailing bits. One doesn't look at the data while the other one does.

The customization provided by the library is meant to configure the implementation, not to adapt to use-cases. This is because the number of possible use-cases is unbounded, while the number of decisions taken in the implementation is finite. So the right design is the one which is currently taken by the library, which is to provide fine granularity control over the implementation. This is the job of the user to define and use the specification adapted to their use-case.

The current configurations have been added to permit to replicate the behavior of other implementations (like the GNU `base64` and `base32` programs) for compatibility reasons. I wasn't aware that some implementations accept invalid length and some users rely on that. I'll add this as a configuration option (see #29).

The algorithm you describe doesn't need this configuration to be efficiently implemented, because `encode_len` which returns the number of base32 characters you need to generate a given number of bytes doesn't return invalid lengths. Something like the following would work fine:
```rust
fn generate(base: &Encoding, len: usize) -> Vec<u8> {
    let input = vec![b'F'; base.encode_len(len)]; // Randomize content.
    base.decode(&input).unwrap()
}
```
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=10165ad74028cae5ec0a2d04efdc1812)
