### ISSUE TITLE
Macros Won't Build in no_std 

### ISSUE THREAD

**Issue by mriise** [ia0/data-encoding#40]
While trying to build with a common `no_std` target `thumbv6m-none-eabi`.
Changing `data-encoding-macro-internal`'s Cargo.toml to use the the alloc feature allowed for a clean build.
`data-encoding = { version = "2.3", path = "../..", default-features = false, features = ["alloc"] }`

`thumbv6m-none-eabi` should probably be added to the CI build list for next time around :)

**Comment by mriise** [comment]
Aaaaand I just read your comment https://github.com/multiformats/rust-multibase/pull/25#issuecomment-720428020

**Comment by ia0** [comment]
The macro doesn't need the `alloc` feature to work, so it shouldn't be necessary to change its dependencies.

The problem is due to https://github.com/rust-lang/cargo/issues/7915 where cargo leaks features of compile-time dependencies like proc-macro. The current fix is to use the `host_dep` unstable feature for now until it gets stable. Does this fix your issue?

**Comment by mriise** [comment]
@ia0 yes, I was going to close this with my last comment but figured it might be good for anyone else who comes across the problem. Maybe a quick note in the README for the macro lib to prevent others falling into the same hole?

**Comment by ia0** [comment]
Good point. I updated the README and documentation.
