### ISSUE TITLE
Rust 2021 edition is a major, not a "patch" change

### ISSUE THREAD

**Issue by link2xt** [ia0/data-encoding#53]
I noticed commit https://github.com/ia0/data-encoding/commit/f8cb34b21726064037ecbe16854f48a7abb4773b

Once you release this as a "patch" you will likely get bug reports that it breaks builds for people using Rust < 1.56.0 and have to yank the version and re-release as major or revert it. This change unnecessarily raises MSRV.

**Comment by ia0** [comment]
Thanks for bringing this issue to my attention! I wasn't aware that it would break the build for old compilers. I'll take a look at it this weekend to see how to address the issue (revert, document, or something else).

**Comment by link2xt** [comment]
I would prefer revert, because https://github.com/deltachat/deltachat-core-rust tries to support Rust >=1.51 (this version introduced const generics which are required by rustcrypto crates) and depends on data-encoding via some crates, including `mailparse` soon.

Also since you have a CI setup, it makes sense to fix some MSRV and automatically test that the crate can still be built with it. If some change breaks compatibility you will notice it and can decide whether it's worth rising the minimum version.

**Comment by ia0** [comment]
Indeed, reverting sounds like the best approach for now, but I'd like to check if there are alternatives before committing. For sure, the priority is to not break users.

Thanks for the CI idea, I'll definitely do that.

**Comment by ia0** [comment]
It looks like there are [no clear guidelines](https://rust-lang.github.io/rfcs/2495-min-rust-version.html#motivation) on how an MSRV bump should impact the crate version. The Rust Embedded WG [only restricts](https://github.com/rust-embedded/wg/blob/master/ops/msrv.md) to the latest stable.

Given that the `data-encoding` library is stable, I'll take the most conservative approach and only bump the MSRV when needed. I'll also do the same for the unstable macro libraries for now, but might revisit this in the future. The binary is out of scope since it cannot break a user build. Similarly, non-exported crates are out of scope.

The smallest MSRV is currently [1.46.0](https://blog.rust-lang.org/2020/08/27/Rust-1.46.0.html) according to [`cargo-msrv`](https://crates.io/crates/cargo-msrv). The MSRV is documented in the [`package.rust-version` field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) of each library and is checked in continuous integration.

If this sounds good to you, I'll submit #54.

Thanks again for bringing this issue to my attention before it was too late!

**Comment by link2xt** [comment]
Checked #54, looks good.

**Comment by ia0** [comment]
Thanks! Merging.
