### ISSUE TITLE
Encode into an "impl std::fmt::Write" and/or "impl std::io::Write"

### ISSUE THREAD

**Issue by dbrgn** [ia0/data-encoding#69]
Sometimes it would be useful to encode directly into a [`std::fmt::Write`](https://doc.rust-lang.org/std/fmt/trait.Write.html), because it would simplify `Display` impls.

```
impl fmt::Display for SomeBytes {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        HEXLOWER.encode_into(&self.0, f)
    }
}
```

In other situations (e.g. network protocols) it's useful to write into a [`std::io::Write`](https://doc.rust-lang.org/std/io/trait.Write.html) impl.

Would these use cases be something that could be added to data-encoding? Or is this already possible through a method I'm missing somehow, without using an intermediate buffer?

**Comment by ia0** [comment]
Thanks for the feature request! This is indeed something I was considering adding. But last time I tried I was not satisfied. I'll give it another try at the end of the month (I currently don't have access to a computer).

**Comment by philpax** [comment]
Hi there! I would also be interested in this for the same reason as the OP. For now I'm just using an intermediate buffer, but it would be great to avoid the allocation. No rush, though 🙂

**Comment by ia0** [comment]
I decided to give up on finding a nice generalization and wrote #91 to unblock this use-case. I'll still try to generalize later when I get more time.

@dbrgn @philpax Do you also need a similar function for decoding? (i.e. something that decodes to a `std::io::Write` because decoding doesn't produce UTF-8 output) Note that this would be much harder to implement which is why I didn't do it yet.

This is how the initial issue would be written once #91 is merged and released:

```rust
impl fmt::Display for SomeBytes {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        HEXLOWER.encode_write(&self.0, f)
    }
}
```

I'm reserving `encode_into()` and `decode_into()` for my generalized function.

**Comment by philpax** [comment]
Decoding would be nice, but not necessary for my use case (iirc, I’d have to check). I’d be happy with just encoding for now!

**Comment by ia0** [comment]
Perfect! Thanks for the feedback.

In that case I'll probably go ahead and merge #91, and eventually release 2.5.0 some time next week (I just want to sleep on it a bit more to be sure I'm not missing something).

I'm planning to provide the same functionality for decoding eventually, but I want to do it as a core functionality rather than some feature on top (essentially for better maintenance, better correctness, better performance, and better usability). But this is going to take much more time than I thought. I already tried a few designs but none of them really convinced me. So at best that would happen before end of next year.
